### ISSUE TITLE
bad interperter

### ISSUE THREAD

**Issue by msauers** [thamarnan/remarkable-custom-template-refresh#1]
I've uploaded the script into the correct directory and set the permissions. When run I get this:

`-sh: ./refresh_template.sh: /bin/bash^M: bad interpreter: No such file or directory`

**Comment by thamarnan** [comment]
How do you upload them?
Are you SCP into it? or copy and paste the source code.

If you copy and paste the source code. make sure to includes every characters in the file.

If you scp it in, which scp client are you using? I'll try on that application.
I've just tested with Filezilla. it's working ok.

**Comment by msauers** [comment]
Opened raw code. Copied & pasted.
Uploaded via winSCP
Logged in via OpenSSH
Screenshots attached
![scp](https://user-images.githubusercontent.com/491936/41814642-1fc61a12-7719-11e8-9e7a-3e26fc91eb43.jpg)
![ssh](https://user-images.githubusercontent.com/491936/41814643-1ffb5998-7719-11e8-91f9-9738aa1618a7.jpg)
![code](https://user-images.githubusercontent.com/491936/41814644-44296738-7719-11e8-8fd6-dc2518cbbd92.jpg)

**Comment by thamarnan** [comment]
looks like problem with CRLF format for Windows vs linux.

Brackets text editor uses the OS default line feed, which is the Windows,
reMarkable expecting the linux format return character hence it renders Windows Return character as ^M
can you try.

Can you try transfer WinSCP using ASCII Mode
so it helps translating the file to correct format when trasfer to target machine (remarkable tablet)

so the solutions are
1) you can use Text Editor that support unix LF character then saved in unix file format and transfer to tablet in binary mode  (WinSCP defaults in Binary mode)

or

2) you can use same Brackets text editor then transfer with WinSCP (ascii mode) to get it translate correctly
https://winscp.net/eng/docs/transfer_mode

**Comment by msauers** [comment]
Well, that solved the existing problem. Seemed to run just fine after ASCII transfer. But now the tablet says I have no available templates. (Restoring original .json file now...)
![ssh2](https://user-images.githubusercontent.com/491936/41815073-7458bb3c-7725-11e8-9ffe-8c8e0e0bf795.jpg)
![no templates](https://user-images.githubusercontent.com/491936/41815083-cd2cbeb6-7725-11e8-9ff5-da780889cce2.jpg)

**Comment by thamarnan** [comment]
can you show me  the copy of the templates.json  after ran the script?
is it empty?

**Comment by msauers** [comment]
Already overwritten with the original to restore functionality. Will re-run in the morning and pull the results. Thanks for working with me on this.

**Comment by msauers** [comment]
Repeated process. Same result. Here's the file post running the script.
https://pastebin.com/4MAVGmQM

**Comment by thamarnan** [comment]
looks like section before APOP is missing one closed bracket.


	,{		"name": "APOP",
		"filename": "APOP",
		"iconCode": "\ue9fe",
		"categories": [
			"Custom"
		]
	}


i've tried rerun the script. it working ok now. just dont edit the templates.json before running it.
